<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EvaluationCriteria;
use App\Models\Role;
use App\Models\CategoryCriteria;

class EvaluationCriteriaSeeder extends Seeder
{
    public function run(): void
    {
        // Lấy id các role theo code
        $roles = Role::pluck('id', 'code'); // ['TP' => 4, 'PP' => 5, 'NV' => 6, ...]
        // Lấy id các category_criteria theo name
        $categories = CategoryCriteria::pluck('id', 'name'); // ['Chính trị, tư tưởng' => 1, ...]

        $criteria = [
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Chính trị, tư tưởng'],
                'name' => 'Chấp hành chủ trương, đường lối, quy định của Đảng, chính sách, pháp luật của Nhà nước và các nguyên tắc tổ chức, kỷ luật của Đảng, nhất là nguyên tắc tập trung dân chủ, tự phê bình và phê bình trong cơ quan, đơn vị',
                'description' => '',
                'max_score' => 5.00,
                'weight' => 1.00,
                'order' => 1,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Không tham ô, tham nhũng, tiêu cực, lãng phí, quan liêu, cơ hội, vụ lợi, hách dịch, cửa quyền; không có biểu hiện suy thoái về đạo đức, lối sống, tự diễn biến, tự chuyển hóa',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 2,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Có lối sống trung thực, khiêm tốn, chân thành, trong sáng, giản dị',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 3,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Có tinh thần đoàn kết, xây dựng cơ quan, đơn vị trong sạch, vững mạnh',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 4,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Không để người thân, người quen lợi dụng vị trí công tác của cá nhân để vụ lợi',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 5,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Có trách nhiệm với công việc, năng động, sáng tạo, dám nghĩ, dám làm, linh hoạt trong thực hiện nhiệm vụ',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 6,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Phương pháp làm việc dân chủ, khoa học, đúng nguyên tắc',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 7,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Có tinh thần trách nhiệm và phối hợp trong thực hiện nhiệm vụ',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 8,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Có thái độ đúng mực và phong cách ứng xử, lề lối làm việc chuẩn mực, đáp ứng văn hóa công vụ và văn hóa của ngành, của cơ quan',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 9,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Chấp hành sự phân công của cơ quan, đơn vị',
                'description' => '',
                'max_score' => 1.5,
                'weight' => 1.00,
                'order' => 10,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Thực hiện đúng các quy định, quy chế của cơ quan',
                'description' => '',
                'max_score' => 1.5,
                'weight' => 1.00,
                'order' => 11,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Tham gia đầy đủ các cuộc họp của Cơ quan, Chi bộ và các tổ chức đoàn thể theo quy định, điều lệ (vắng phải có lý do chính đáng)',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 12,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Báo cáo đúng hạn, trung thực, đầy đủ, cung cấp thông tin chính xác, khách quan về những nội dung liên quan đến việc thực hiện chức trách, nhiệm vụ được giao và hoạt động của cơ quan, đơn vị khi được yêu cầu',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 13,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Sử dụng đầy đủ, đúng quy định các phần mềm, nền tảng số triển khai trong cơ quan',
                'description' => '',
                'max_score' => 3.00,
                'weight' => 1.00,
                'order' => 14,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Có sáng kiến, giải pháp mới trong việc thực hiện cải cách hành chính ở cơ quan',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 15,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Tham gia đầy đủ và đạt kết quả tốt các lớp tập huấn được phân công',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 16,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Không có phản ánh về tinh thần, thái độ phục vụ Nhân dân',
                'description' => '',
                'max_score' => 3.00,
                'weight' => 1.00,
                'order' => 17,
                'is_active' => true,
            ],
            // ===== NHÓM II: KẾT QUẢ THỰC HIỆN NHIỆM VỤ, CHỨC TRÁCH ĐƯỢC GIAO (70 điểm) =====
            // 1. Năng lực lãnh đạo, quản lý (10 điểm)
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Chủ động nghiên cứu, cập nhật kịp thời các quy định của pháp luật, của ngành về lĩnh vực phụ trách; tham mưu cho BGĐ đầy đủ, có chất lượng các văn bản phục vụ chỉ đạo, điều hành của Lãnh đạo tỉnh và Lãnh đạo UBND',
                'description' => 'Sai sót chủ quan 01 nhiệm vụ trừ 0,25 điểm. Điểm trừ không quá 01 điểm',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 18,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Xây dựng kế hoạch công tác của phòng/đơn vị theo lĩnh vực được phân công và kế hoạch công tác của cá nhân rõ nội dung và tiến độ',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 19,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Chỉ đạo, điều hành, kiểm soát việc thực hiện của phòng/đơn vị phụ trách bảo đảm kịp thời, không bỏ sót nhiệm vụ. Giải quyết công việc đúng quy trình, quy định',
                'description' => 'Sai sót chủ quan 01 nhiệm vụ trừ 0,25 điểm. Điểm trừ không quá 01 điểm',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 20,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Kiểm tra, bao quát, đôn đốc việc thực hiện nhiệm vụ của CCVC trong phòng/đơn vị và giải quyết kịp thời các khó khăn, vướng mắc theo thẩm quyền',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 21,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Tham mưu chỉ đạo, hướng dẫn chuyên môn, nghiệp vụ đối với các tổ chức, cơ quan, đơn vị trong lĩnh vực phụ trách bảo đảm hiệu quả, thống nhất',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 22,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Chủ động tham mưu, đề xuất nhiệm vụ, công việc có liên quan đến lĩnh vực được giao phụ trách; Báo cáo kịp thời kết quả nhiệm vụ được giao',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 23,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Phối hợp với các phòng/đơn vị khác trong cơ quan khi thực hiện nhiệm vụ, chức trách được giao bảo đảm thống nhất, nhanh chóng, hiệu quả',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 24,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Lãnh đạo phòng/đơn vị phụ trách làm việc hiệu quả; thực hiện CCHC; chuyển đổi số; thực hiện quản lý CCVC theo phân cấp, phân quyền',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 25,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Các văn bản do phòng/đơn vị tham mưu phải bảo đảm đúng thể thức, quy trình, quy định, thủ tục ban hành, không có sai sót và phải đúng hạn theo quy định của Sở, của tỉnh',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 26,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Có năng lực tập hợp CCVC trong phòng/đơn vị đoàn kết, thống nhất',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 27,
                'is_active' => true,
            ],
            // 2. Thực hiện nhiệm vụ theo kế hoạch, lịch công tác và nhiệm vụ đột xuất đúng tiến độ, chất lượng (55 điểm)
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Kết quả thực hiện nhiệm vụ, chức trách được giao'],
                'name' => 'Kết quả thực hiện nhiệm vụ của phòng/đơn vị - Xếp loại A/B/C/D',
                'description' => '',
                'max_score' => 55.00,
                'weight' => 1.00,
                'order' => 28,
                'is_active' => true,
            ],
            // 3. Có sáng kiến trong triển khai nhiệm vụ chuyên môn theo chức năng, nhiệm vụ được giao (5 điểm)
            [
                'role_id' => $roles['TP'],
                'category_criteria_id' => $categories['Kết quả thực hiện nhiệm vụ, chức trách được giao'],
                'name' => 'Có sáng kiến trong triển khai nhiệm vụ chuyên môn theo chức năng, nhiệm vụ được giao',
                'description' => '',
                'max_score' => 5.00,
                'weight' => 1.00,
                'order' => 32,
                'is_active' => true,
            ],

            // ===== TIÊU CHÍ CHO PHÓ PHÒNG (CHI TIẾT) =====
            // ===== NHÓM I: CHÍNH TRỊ, TƯ TƯỞNG; ĐẠO ĐỨC, LỐI SỐNG; TÁC PHONG, LỀ LỐI LÀM VIỆC; Ý THỨC TỔ CHỨC KỶ LUẬT; THỰC HIỆN CHUYỂN ĐỔI SỐ VÀ CẢI CÁCH HÀNH CHÍNH (30 điểm) =====
            // 1. Chính trị, tư tưởng (5 điểm)
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Chính trị, tư tưởng'],
                'name' => 'Chấp hành chủ trương, đường lối, quy định của Đảng, chính sách, pháp luật của Nhà nước và các nguyên tắc tổ chức, kỷ luật của Đảng, nhất là nguyên tắc tập trung dân chủ, tự phê bình và phê bình trong cơ quan, đơn vị',
                'description' => '',
                'max_score' => 5.00,
                'weight' => 1.00,
                'order' => 1,
                'is_active' => true,
            ],
            // 2. Đạo đức, lối sống (5 điểm, tách nhỏ)
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Không tham ô, tham nhũng, tiêu cực, lãng phí, quan liêu, cơ hội, vụ lợi, hách dịch, cửa quyền; không có biểu hiện suy thoái về đạo đức, lối sống, tự diễn biến, tự chuyển hóa',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 2,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Có lối sống trung thực, khiêm tốn, chân thành, trong sáng, giản dị',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 3,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Có tinh thần đoàn kết, xây dựng cơ quan, đơn vị trong sạch, vững mạnh',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 4,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Không để người thân, người quen lợi dụng vị trí công tác của cá nhân để vụ lợi',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 5,
                'is_active' => true,
            ],
            // 3. Tác phong, lề lối làm việc (5 điểm, tách nhỏ)
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Có trách nhiệm với công việc, năng động, sáng tạo, dám nghĩ, dám làm, linh hoạt trong thực hiện nhiệm vụ',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 6,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Phương pháp làm việc dân chủ, khoa học, đúng nguyên tắc',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 7,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Có tinh thần trách nhiệm và phối hợp trong thực hiện nhiệm vụ',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 8,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Có thái độ đúng mực và phong cách ứng xử, lề lối làm việc chuẩn mực, đáp ứng văn hóa công vụ và văn hóa của ngành, của cơ quan',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 9,
                'is_active' => true,
            ],
            // 4. Ý thức tổ chức kỷ luật (5 điểm, tách nhỏ)
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Chấp hành sự phân công của cơ quan, đơn vị',
                'description' => '',
                'max_score' => 1.5,
                'weight' => 1.00,
                'order' => 10,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Thực hiện đúng các quy định, quy chế của cơ quan',
                'description' => '',
                'max_score' => 1.5,
                'weight' => 1.00,
                'order' => 11,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Tham gia đầy đủ các cuộc họp của Cơ quan, Chi bộ và các tổ chức đoàn thể theo quy định, điều lệ (vắng phải có lý do chính đáng)',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 12,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Báo cáo đúng hạn, trung thực, đầy đủ, cung cấp thông tin chính xác, khách quan về những nội dung liên quan đến việc thực hiện chức trách, nhiệm vụ được giao và hoạt động của cơ quan, đơn vị khi được yêu cầu',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 13,
                'is_active' => true,
            ],
            // 5. Thực hiện chuyển đổi số và cải cách hành chính (10 điểm, tách nhỏ)
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Sử dụng đầy đủ, đúng quy định các phần mềm, nền tảng số triển khai trong cơ quan',
                'description' => '',
                'max_score' => 3.00,
                'weight' => 1.00,
                'order' => 14,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Có sáng kiến, giải pháp mới trong việc thực hiện CCHC ở cơ quan',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 15,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Tham gia đầy đủ và đạt kết quả tốt các lớp tập huấn được phân công',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 16,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Không có phản ánh về tinh thần, thái độ phục vụ Nhân dân',
                'description' => '',
                'max_score' => 3.00,
                'weight' => 1.00,
                'order' => 17,
                'is_active' => true,
            ],
            // ===== NHÓM II: KẾT QUẢ THỰC HIỆN NHIỆM VỤ, CHỨC TRÁCH ĐƯỢC GIAO (70 điểm) =====
            // 1. Năng lực lãnh đạo, quản lý (10 điểm)
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Chủ động nghiên cứu, cập nhật kịp thời các quy định của pháp luật, của ngành về lĩnh vực phụ trách; tham mưu cho Ban lãnh đạo đầy đủ, có chất lượng các văn bản phục vụ chỉ đạo, điều hành của Lãnh đạo tỉnh và Lãnh đạo UBND xã',
                'description' => 'Sai sót chủ quan 01 nhiệm vụ trừ 0,25 điểm. Điểm trừ không quá 01 điểm',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 18,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Xây dựng kế hoạch công tác của phòng/đơn vị theo lĩnh vực được phân công và kế hoạch công tác của cá nhân rõ nội dung và tiến độ',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 19,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Chỉ đạo, điều hành, kiểm soát việc thực hiện của phòng/đơn vị phụ trách bảo đảm kịp thời, không bỏ sót nhiệm vụ. Giải quyết công việc đúng quy trình, quy định',
                'description' => 'Sai sót chủ quan 01 nhiệm vụ trừ 0,25 điểm. Điểm trừ không quá 01 điểm',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 20,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Kiểm tra, bao quát, đôn đốc việc thực hiện nhiệm vụ của CCVC trong phòng/đơn vị và giải quyết kịp thời các khó khăn, vướng mắc theo thẩm quyền',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 21,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Tham mưu chỉ đạo, hướng dẫn chuyên môn, nghiệp vụ đối với các tổ chức, cơ quan, đơn vị trong lĩnh vực phụ trách đảm bảo hiệu quả, thống nhất',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 22,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Chủ động tham mưu, đề xuất nhiệm vụ, công việc có liên quan đến lĩnh vực được giao phụ trách; Báo cáo kịp thời kết quả nhiệm vụ được giao',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 23,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Phối hợp với các phòng/đơn vị khác trong cơ quan khi thực hiện nhiệm vụ, chức trách được giao bảo đảm thống nhất, nhanh chóng, hiệu quả',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 24,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Lãnh đạo phòng/đơn vị phụ trách làm việc hiệu quả; thực hiện CCHC; chuyển đổi số; thực hiện quản lý CCVC theo phân cấp, phân quyền',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 25,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Các văn bản do phòng/đơn vị tham mưu phải bảo đảm đúng thể thức, quy trình, quy định, thủ tục ban hành, không có sai sót và phải đúng hạn theo quy định của Sở, của tỉnh',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 26,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Năng lực lãnh đạo, quản lý'],
                'name' => 'Có năng lực tập hợp CCVC trong phòng/đơn vị đoàn kết, thống nhất',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 27,
                'is_active' => true,
            ],
            // 2. Thực hiện nhiệm vụ theo kế hoạch, lịch công tác và nhiệm vụ đột xuất đúng tiến độ, chất lượng (55 điểm)
            // 2.1. Kết quả thực hiện nhiệm vụ của phòng/đơn vị (10 điểm)
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Kết quả thực hiện nhiệm vụ, chức trách được giao'],
                'name' => 'Kết quả thực hiện nhiệm vụ của phòng/đơn vị - Xếp loại A/B/C/D',
                'description' => '',
                'max_score' => 10.00,
                'weight' => 1.00,
                'order' => 28,
                'is_active' => true,
            ],
            // 2.2. Thực hiện nhiệm vụ theo kế hoạch, lịch công tác và nhiệm vụ đột xuất đúng tiến độ, chất lượng (45 điểm)
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Kết quả thực hiện nhiệm vụ, chức trách được giao'],
                'name' => 'Thực hiện nhiệm vụ theo kế hoạch, lịch công tác và nhiệm vụ đột xuất đúng tiến độ, chất lượng - Mức độ Đạt vượt mức/ Đạt/ Đạt, còn hạn chế/ Không đạt',
                'description' => '',
                'max_score' => 45.00,
                'weight' => 1.00,
                'order' => 29,
                'is_active' => true,
            ],
            // 3. Có sáng kiến trong triển khai nhiệm vụ chuyên môn theo chức năng, nhiệm vụ được giao (5 điểm)
            [
                'role_id' => $roles['PP'],
                'category_criteria_id' => $categories['Kết quả thực hiện nhiệm vụ, chức trách được giao'],
                'name' => 'Có sáng kiến trong triển khai nhiệm vụ chuyên môn theo chức năng, nhiệm vụ được giao',
                'description' => '',
                'max_score' => 5.00,
                'weight' => 1.00,
                'order' => 33,
                'is_active' => true,
            ],

            // ===== TIÊU CHÍ CHO NHÂN VIÊN (CHI TIẾT) =====
            // ===== NHÓM I: CHÍNH TRỊ, TƯ TƯỞNG; ĐẠO ĐỨC, LỐI SỐNG; TÁC PHONG, LỀ LỐI LÀM VIỆC; Ý THỨC TỔ CHỨC KỶ LUẬT; THỰC HIỆN CHUYỂN ĐỔI SỐ VÀ CẢI CÁCH HÀNH CHÍNH (30 điểm) =====
            // 1. Chính trị, tư tưởng (5 điểm)
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Chính trị, tư tưởng'],
                'name' => 'Chấp hành chủ trương, đường lối, quy định của Đảng, chính sách, pháp luật của Nhà nước và các nguyên tắc tổ chức, kỷ luật của Đảng, nhất là nguyên tắc tập trung dân chủ, tự phê bình và phê bình trong cơ quan, đơn vị',
                'description' => '',
                'max_score' => 5.00,
                'weight' => 1.00,
                'order' => 1,
                'is_active' => true,
            ],
            // 2. Đạo đức, lối sống (5 điểm, tách nhỏ)
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Không tham ô, tham nhũng, tiêu cực, lãng phí, quan liêu, cơ hội, vụ lợi, hách dịch, cửa quyền; không có biểu hiện suy thoái về đạo đức, lối sống, tự diễn biến, tự chuyển hóa',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 2,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Có lối sống trung thực, khiêm tốn, chân thành, trong sáng, giản dị',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 3,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Có tinh thần đoàn kết, xây dựng cơ quan, tổ chức, đơn vị trong sạch, vững mạnh',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 4,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Đạo đức, lối sống'],
                'name' => 'Không để người thân, người quen lợi dụng vị trí công tác của cá nhân để vụ lợi',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 5,
                'is_active' => true,
            ],
            // 3. Tác phong, lề lối làm việc (5 điểm, tách nhỏ)
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Có trách nhiệm với công việc, năng động, sáng tạo, dám nghĩ, dám làm, linh hoạt trong thực hiện nhiệm vụ',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 6,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Phương pháp làm việc dân chủ, khoa học, đúng nguyên tắc',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 7,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Có tinh thần trách nhiệm và phối hợp trong thực hiện nhiệm vụ',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 8,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Tác phong, lề lối làm việc'],
                'name' => 'Có thái độ đúng mực và phong cách ứng xử, lề lối làm việc chuẩn mực, đáp ứng văn hóa công vụ và văn hóa của ngành, của cơ quan',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 9,
                'is_active' => true,
            ],
            // 4. Ý thức tổ chức kỷ luật (5 điểm, tách nhỏ)
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Chấp hành sự phân công của cơ quan, đơn vị',
                'description' => '',
                'max_score' => 1.5,
                'weight' => 1.00,
                'order' => 10,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Thực hiện đúng các quy định, quy chế của cơ quan',
                'description' => '',
                'max_score' => 1.5,
                'weight' => 1.00,
                'order' => 11,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Tham gia đầy đủ các cuộc họp của Cơ quan, Chi bộ và các tổ chức đoàn thể theo quy định, điều lệ (vắng phải có lý do chính đáng)',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 12,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Ý thức tổ chức kỷ luật'],
                'name' => 'Báo cáo đúng hạn, trung thực, đầy đủ, cung cấp thông tin chính xác, khách quan về những nội dung liên quan đến việc thực hiện chức trách, nhiệm vụ được giao và hoạt động của cơ quan, đơn vị khi được yêu cầu',
                'description' => '',
                'max_score' => 1.00,
                'weight' => 1.00,
                'order' => 13,
                'is_active' => true,
            ],
            // 5. Thực hiện chuyển đổi số và cải cách hành chính (10 điểm, tách nhỏ)
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Sử dụng đầy đủ, đúng quy định các phần mềm, nền tảng số triển khai trong cơ quan',
                'description' => '',
                'max_score' => 3.00,
                'weight' => 1.00,
                'order' => 14,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Có sáng kiến, giải pháp mới trong việc thực hiện CCHC ở cơ quan',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 15,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Tham gia đầy đủ và đạt kết quả tốt các lớp tập huấn được phân công',
                'description' => '',
                'max_score' => 2.00,
                'weight' => 1.00,
                'order' => 16,
                'is_active' => true,
            ],
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Thực hiện chuyển đổi số và cải cách hành chính'],
                'name' => 'Không có phản ánh về tinh thần, thái độ phục vụ Nhân dân',
                'description' => '',
                'max_score' => 3.00,
                'weight' => 1.00,
                'order' => 17,
                'is_active' => true,
            ],
            // ===== NHÓM II: KẾT QUẢ THỰC HIỆN NHIỆM VỤ, CHỨC TRÁCH ĐƯỢC GIAO (70 điểm) =====
            // 1. Kết quả thực hiện nhiệm vụ của phòng/đơn vị (10 điểm)
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Kết quả thực hiện nhiệm vụ, chức trách được giao'],
                'name' => 'Kết quả thực hiện nhiệm vụ của phòng/đơn vị - Xếp loại A/B/C/D',
                'description' => '',
                'max_score' => 10.00,
                'weight' => 1.00,
                'order' => 18,
                'is_active' => true,
            ],
            // 2. Thực hiện nhiệm vụ theo kế hoạch, lịch công tác và nhiệm vụ đột xuất đúng tiến độ, chất lượng (55 điểm)
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Kết quả thực hiện nhiệm vụ, chức trách được giao'],
                'name' => 'Thực hiện nhiệm vụ theo kế hoạch, lịch công tác và nhiệm vụ đột xuất đúng tiến độ, chất lượng - Mức độ Đạt vượt mức/ Đạt/ Đạt, còn hạn chế/ Không đạt',
                'description' => '',
                'max_score' => 55.00,
                'weight' => 1.00,
                'order' => 19,
                'is_active' => true,
            ],
            // 3. Có sáng kiến trong triển khai nhiệm vụ chuyên môn theo chức năng, nhiệm vụ được giao (5 điểm)
            [
                'role_id' => $roles['NV'],
                'category_criteria_id' => $categories['Kết quả thực hiện nhiệm vụ, chức trách được giao'],
                'name' => 'Có sáng kiến trong triển khai nhiệm vụ chuyên môn theo chức năng, nhiệm vụ được giao',
                'description' => '',
                'max_score' => 5.00,
                'weight' => 1.00,
                'order' => 20,
                'is_active' => true,
            ],
        ];

        // Đánh lại order cho từng nhóm role_id + category_criteria_id
        $orderMap = [];
        foreach ($criteria as $i => $criterion) {
            $key = $criterion['role_id'] . '-' . $criterion['category_criteria_id'];
            if (!isset($orderMap[$key])) {
                $orderMap[$key] = 1;
            }
            $criteria[$i]['order'] = $orderMap[$key];
            $orderMap[$key]++;
        }

        foreach ($criteria as $criterion) {
            EvaluationCriteria::create($criterion);
        }
    }
} 